version: '2'

services:

  nacos:
    image: nacos/nacos-server
    container_name: nacos
    restart: always
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - JVM_XMS=256m
      - JVM_XMX=256m
    volumes:
      - /data/nacos-server/logs/:/home/nacos/logs
    ports:
      - 8848:8848